name: doc_verifier_flutter
description: A Flutter web app for verifying documents and extracting metadata.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0

flutter:
  uses-material-design: true
